resources:
  - ../../../crd

labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      app.kubernetes.io/name: dkim-manager

patches:
  - path: conversion-patch.yaml

transformers:
  - label-transformer.yaml
